-- Tabla de doctores
CREATE TABLE doctors
(
    "id_doctor" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_user"   BIGINT       NOT NULL,
    "specialty" VARCHAR(255) NOT NULL,
    "phone"     VARCHAR(15),
    "active"    BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_doctor_user FOREIGN KEY ("id_user") REFERENCES users ("id_user") ON DELETE CASCADE
);

-- Tabla de pacientes
CREATE TABLE patients
(
    "id_patient"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_user"            BIGINT  NOT NULL,
    "id_doctor"          BIGINT  NOT NULL,
    "age"                INT     NOT NULL,
    "gender"             CHAR(1) NOT NULL CHECK ("gender" IN ('M', 'F')),
    "weight"             FLOAT   NOT NULL,
    "height"             FLOAT   NOT NULL,
    "medical_conditions" TEXT,
    "registration_date"  DATE    NOT NULL,
    "active"             BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_patient_user FOREIGN KEY ("id_user") REFERENCES users ("id_user") ON DELETE CASCADE,
    CONSTRAINT fk_patient_doctor FOREIGN KEY ("id_doctor") REFERENCES doctors ("id_doctor") ON DELETE SET NULL
);

-- Índices (opcional, pero recomendado para mejorar el rendimiento en consultas)
CREATE INDEX idx_doctor_user ON doctors ("id_user");
CREATE INDEX idx_patient_user ON patients ("id_user");
CREATE INDEX idx_patient_doctor ON patients ("id_doctor");