-- Crear tabla recommendations
CREATE TABLE recommendations
(
    id_recommendation BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content           TEXT    NOT NULL,
    active            BOOLEAN NOT NULL DEFAULT TRUE
);

-- Crear tabla intermedia strata_recommendations
CREATE TABLE strata_recommendations
(
    id_stratum        BIGINT NOT NULL,
    id_recommendation BIGINT NOT NULL,
    PRIMARY KEY (id_stratum, id_recommendation),
    CONSTRAINT fk_stratum FOREIGN KEY (id_stratum) REFERENCES strata (id_stratum) ON DELETE CASCADE,
    CONSTRAINT fk_recommendation FOREIGN KEY (id_recommendation) REFERENCES recommendations (id_recommendation) ON DELETE CASCADE
);

-- Agregar la columna id_stratum a la tabla patients
ALTER TABLE patients
    ADD COLUMN id_stratum BIGINT;

-- Agregar la restricción de clave foránea para id_stratum
ALTER TABLE patients
    ADD CONSTRAINT fk_patient_stratum FOREIGN KEY (id_stratum) REFERENCES strata (id_stratum) ON DELETE CASCADE;

-- Crear índices para mejorar el rendimiento
CREATE INDEX idx_stratum_recommendation_stratum ON strata_recommendations (id_stratum);
CREATE INDEX idx_stratum_recommendation_recommendation ON strata_recommendations (id_recommendation);
